# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('energy', models.CharField(max_length=100)),
                ('protein', models.CharField(max_length=100)),
                ('fat', models.CharField(max_length=100)),
                ('sugar', models.CharField(max_length=100)),
                ('fibre', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('picture', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('foodname', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=5)),
                ('satfat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fibre', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sugar', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sodium', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'food',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('f1', models.CharField(blank=True, db_column='F1', max_length=100, null=True)),
                ('f2', models.CharField(blank=True, db_column='F2', max_length=100, null=True)),
                ('f3', models.CharField(blank=True, db_column='F3', max_length=100, null=True)),
                ('f4', models.CharField(blank=True, db_column='F4', max_length=100, null=True)),
                ('f5', models.CharField(blank=True, db_column='F5', max_length=100, null=True)),
                ('f6', models.CharField(blank=True, db_column='F6', max_length=100, null=True)),
                ('f7', models.CharField(blank=True, db_column='F7', max_length=100, null=True)),
                ('f8', models.CharField(blank=True, db_column='F8', max_length=100, null=True)),
                ('f9', models.CharField(blank=True, db_column='F9', max_length=100, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
